version: 2 
jobs: 
  build: 
    working_directory: ~/topcoder-account-smoke-test 
    docker: 
      - image: circleci/node:11-browsers 
    steps: 
      - checkout 
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: browser Update
          command: './node_modules/.bin/webdriver-manager update'      
      - run: 
          name: browser start
          command: './node_modules/.bin/webdriver-manager start'   
          background: true    
      - run: # run tests
          name: Execute Smoke Test
          command: npm test
      # - run: # For TestQuality
      #     name: TestQuality Login/Upload file to Test TestQuality Server
      #     command: |
      #       sudo chmod 755 testquality-linux
      #       ./testquality-linux login drasticdpk@gmail.com Testquality@100 --save
      #       ./testquality-linux upload_test_run junitresults.xml --project_name='protractor-jasmine-typescript' --plan_name='Smoke Test'
      #     when: always

   
